[start]
call_from_id = [""] # ID –ª—é–¥–µ–π, –∫–æ—Ç–æ—Ä—ã–µ –±—É–¥—É—Ç –≤—ã–∑—ã–≤–∞—Ç—å –±–æ—Ç–∞
group_id = [""] # ID –≥—Ä—É–ø–ø, –∫–æ—Ç–æ—Ä—ã–µ –±—É–¥—É—Ç —Ä–µ–∞–≥–∏—Ä–æ–≤–∞—Ç—å –Ω–∞ —ç—Ç—É –∫–æ–º–∞–Ω–¥—É

text_mode = "1" # –†–µ–∂–∏–º –æ—Ç–ø—Ä–∞–≤–ª—è–µ–º–æ–≥–æ —Ç–µ–∫—Å—Ç–∞. 1 - —Å—Ç–∞–Ω–¥–∞—Ä—Ç–Ω—ã–π —Ä–µ–∂–∏–º, 2 - —Ä–µ–∂–∏–º –ø–æ—Å—Ç—Ä–æ—á–Ω–æ, 3 - —Ä–µ–∂–∏–º –æ–±—Ä–µ–∑–∫–∏ —á–µ—Ä–µ–∑ —Å–∏–º–≤–æ–ª "\\" (–æ–¥–Ω—É back slash, —Ç–∞–∫ –∫–∞–∫ –æ–Ω–∞ –∫–æ–Ω—Ñ–ª–∏–∫—Ç—É–µ—Ç –≥–¥–µ —Ç–æ–ª—å–∫–æ –º–æ–∂–Ω–æ) (–Ω—É–∂–Ω–æ –ø–∏—Å–∞—Ç—å \\, –µ—Å–ª–∏ –¥–µ–ª–∞–µ—Ç–µ —ç—Ç–æ –ª–æ–∫–∞–ª—å–Ω–æ, —á—Ç–æ–±—ã –Ω–µ –±—ã–ª–æ –æ—à–∏–±–æ–∫)
random_text = "0" # –°–ª—É—á–∞–π–Ω–æ –æ—Ç–ø—Ä–∞–≤–ª—è–µ—Ç —Ç–µ–∫—Å—Ç –∏–∑ —Ä–µ–∂–∏–º–∞ —Ç–µ–∫—Å—Ç–∞ 2. 0 - –≤—ã–∫–ª—é—á–µ–Ω, 1 - –≤–∫–ª—é—á–µ–Ω
text = "üëπ" # –¢–µ–∫—Å—Ç —Å–æ–æ–±—â–µ–Ω–∏—è
attachment = [""] # –û—Ç–ø—Ä–∞–≤–ª—è–µ—Ç –ª—é–±–æ–µ –∏–∑ –ø–µ—Ä–µ—á–∏—Å–ª–µ–Ω–Ω—ã—Ö –≤–ª–æ–∂–µ–Ω–∏–π: 'photo' ‚Äî —Ñ–æ—Ç–æ, 'video' ‚Äî –≤–∏–¥–µ–æ, 'audio' ‚Äî –∞—É–¥–∏–æ, 'doc' ‚Äî –¥–æ–∫—É–º–µ–Ω, 'wall' ‚Äî –ø–æ—Å—Ç –Ω–∞ —Å—Ç–µ–Ω–µ. –§–æ—Ä–º–∞—Ç –ø–æ–¥–ø–∏—Å–∏ —Ç–∞–∫–æ–π: <–í–ª–æ–∂–µ–Ω–∏–µ><–í–ª–∞–¥–µ–ª–µ—Ü —ç—Ç–æ–≥–æ –≤–ª–æ–∂–µ–Ω–∏—è>_<id –≤–ª–æ–∂–µ–Ω–∏—è>, –ø—Ä–∏–º–µ—Ä: photo514714577_457311228
random_attachment = "0" # –°–ª—É—á–∞–π–Ω–æ –æ—Ç–ø—Ä–∞–≤–ª—è–µ—Ç –∏–∑ –≤–ø–∏—Å–∞–Ω–Ω—ã—Ö –≤–ª–æ–∂–µ–Ω–∏–π. 0 - –≤—ã–∫–ª—é—á–µ–Ω, 1 - –≤–∫–ª—é—á–µ–Ω

button_mode = "1" # –í–∏–¥ –æ—Ç–ø—Ä–∞–≤–ª—è–µ–º—ã—Ö –∫–Ω–æ–ø–æ–∫. 1 - —Å—Ç–∞–Ω–¥–∞—Ä—Ç–Ω—ã–π —Ä–µ–∂–∏–º, 2 - —Ä–µ–∂–∏–º —Ä–∞–¥—É–≥–∏, 3 - —Ä–µ–∂–∏–º –≤–∏—Ä—É—Å–∞, 4 - —Ä–µ–∂–∏–º –∏–∑ –±–æ—Ç–∞ "sparta raid", 0 - –≤—ã–∫–ª—é—á–∏—Ç—å –∫–Ω–æ–ø–∫–∏

mode1_button_color1 = "2" # –¶–≤–µ—Ç –∫–Ω–æ–ø–∫–∏ 1 –¥–ª—è —Ä–µ–∂–∏–º–∞ 1. 0 - –∑–µ–ª—ë–Ω–∞—è, 1 - –∫—Ä–∞—Å–Ω–∞—è, 2 - —Å–∏–Ω—è—è, 3 - —Å–µ—Ä–∞—è
mode1_button_color2 = "1" # –¶–≤–µ—Ç –∫–Ω–æ–ø–∫–∏ 2 –¥–ª—è —Ä–µ–∂–∏–º–∞ 1. 0 - –∑–µ–ª—ë–Ω–∞—è, 1 - –∫—Ä–∞—Å–Ω–∞—è, 2 - —Å–∏–Ω—è—è, 3 - —Å–µ—Ä–∞—è
mode1_button_color3 = "2" # –¶–≤–µ—Ç –∫–Ω–æ–ø–∫–∏ 3 –¥–ª—è —Ä–µ–∂–∏–º–∞ 1. 0 - –∑–µ–ª—ë–Ω–∞—è, 1 - –∫—Ä–∞—Å–Ω–∞—è, 2 - —Å–∏–Ω—è—è, 3 - —Å–µ—Ä–∞—è
mode1_button_color4 = "3" # –¶–≤–µ—Ç –∫–Ω–æ–ø–∫–∏ 4 –¥–ª—è —Ä–µ–∂–∏–º–∞ 1. 0 - –∑–µ–ª—ë–Ω–∞—è, 1 - –∫—Ä–∞—Å–Ω–∞—è, 2 - —Å–∏–Ω—è—è, 3 - —Å–µ—Ä–∞—è

mode1_2_3_button_text1 = "–û–°–¢–ê–ù–û–í–ò–¢–¨ –ë–ï–ó–£–ú–ò–ï" # –¢–µ–∫—Å—Ç –∫–Ω–æ–ø–∫–∏ 1 –¥–ª—è —Ä–µ–∂–∏–º–æ–≤ 1, 2 –∏ 3
mode1_2_3_button_text2 = "Text2" # –¢–µ–∫—Å—Ç –∫–Ω–æ–ø–∫–∏ 2 –¥–ª—è —Ä–µ–∂–∏–º–æ–≤ 1, 2 –∏ 3
mode1_2_3_button_text3 = "Text3" # –¢–µ–∫—Å—Ç –∫–Ω–æ–ø–∫–∏ 3 –¥–ª—è —Ä–µ–∂–∏–º–æ–≤ 1, 2 –∏ 3
mode1_2_3_button_text4 = "Text4" # –¢–µ–∫—Å—Ç –∫–Ω–æ–ø–∫–∏ 4 –¥–ª—è —Ä–µ–∂–∏–º–æ–≤ 1, 2 –∏ 3

message_counter_limit = "-1" # –û—Ç–ø—Ä–∞–≤–ª—è–µ—Ç n-–æ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Å–æ–æ–±—â–µ–Ω–∏–π, –∞ –ø–æ—Å–ª–µ –ø–µ—Ä–µ—Å—Ç–∞—ë—Ç —Ä–∞–±–æ—Ç–∞—Ç—å. –ß—Ç–æ–±—ã —Å–ø–∞–º–∏–ª–æ –±–µ—Å–∫–æ–Ω–µ—á–Ω–æ, –Ω—É–∂–Ω–æ —Å—Ç–∞–≤–∏—Ç—å –æ—Ç—Ä–∏—Ü–∞—Ç–µ–ª—å–Ω—ã–µ —á–∏—Å–ª–∞ (-1 –∫ –ø—Ä–∏–º–µ—Ä—É)

delay = "1.0" # –ó–∞–¥–µ—Ä–∂–∫–∞ –ø–µ—Ä–µ–¥ –æ—Ç–ø—Ä–∞–≤–∫–æ–π —Å–ª–µ–¥—É—é—â–µ–≥–æ —Å–æ–æ–±—â–µ–Ω–∏—è
delay_kill = "10.0" # –ó–∞–¥–µ—Ä–∂–∫–∞ –ø–µ—Ä–µ–¥ –æ—Ç–ø—Ä–∞–≤–∫–æ–π —Å–ª–µ–¥—É—é—â–µ–≥–æ —Å–æ–æ–±—â–µ–Ω–∏—è –ø–æ—Å–ª–µ –æ—à–∏–±–∫–∏
